- hosts: k3node1
  roles:
  - role: hifis.keepalived
    vars:
      keepalived_unicast_src_ip: '10.0.0.210'
      keepalived_interface: "eth0"
      keepalived_virtual_ip_address: '10.0.1.64'
      keepalived_unicast_peers:
      - '10.0.1.29'
      - '10.0.1.249'
      keepalived_conf_file_path: '/etc/keepalived/keepalived.conf'
      keepalived_state: 'BACKUP'
      keepalived_priority: '99'
      keepalived_router_id: 'KEEPALIVED_K3S'
      keepalived_auth_pass: '883105'
      keepalived_enable_process_tracking: false
