---
- name: Configure kube1 hosts
  hosts: backup_node_1
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.keepalived
      keepalived_vrrp_instances:
        - name: VI_1
          state: BACKUP
          interface: eth0
          unicast_src_ip: "10.0.1.249"
          secondary_private_ip: "10.0.1.248"
          virtual_router_id: 51
          priority: 200
          authentication:
            auth_type: PASS
            auth_pass: "310588"
          virtual_ipaddresses:
            - name: "10.0.1.64"
              cidr: 23
