---
- name: Converge
  hosts: master_node
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.keepalived
      keepalived_vrrp_instances:
        - name: VI_1
          state: MASTER
          interface: eth0
          unicast_src_ip: "10.0.0.210"
          secondary_private_ip: "10.0.0.211"
          virtual_router_id: 51
          priority: 255
          authentication:
            auth_type: PASS
            auth_pass: "310588"
          virtual_ipaddresses:
            - name: "10.0.1.64"
              cidr: 23
