version: '3'
services:
  reverse:
    container_name: homelab-nginx2
    image: nginx
    hostname: homelab-nginx2
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/plex.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/plextrahdev.conf:/etc/nginx/conf.d/plexdev.conf
      - ./nginx/pgadmin.conf:/etc/nginx/conf.d/pgadmin.conf
      - ./nginx/portainer.conf:/etc/nginx/conf.d/portainer.conf
      - /etc/letsencrypt/:/etc/nginx/certs:ro
    networks:
      physical_net:
        ipv4_address: 10.0.1.97
networks:
  physical_net:
    external: true
