version: "3.8"
services:
  nginx:
    image: git.trahan.dev/jtrahan/nginx:dev
    restart: unless-stopped
    volumes:
      - /mnt/trahan-nas/swarm-vols/nginx-1/configs/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/trahan-nas/swarm-vols/nginx-1/configs/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/:/etc/nginx/certs:ro
    networks:
      - ovnet1
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 2
networks:
  ovnet1:
    external: true
    name: ovnet1
