apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: data-volume
          mountPath: /prometheus
        resources:
          limits:
            cpu: "500m" # 500 millicores (0.5 CPU)
            memory: "1Gi" # 256 MiB memory
          requests:
            cpu: "250m" # Request 0.25 CPU initially
            memory: "512Mi"
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-server-conf
          defaultMode: 420
      - name: data-volume
        persistentVolumeClaim:
          claimName: pvc-prometheus
