apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: node-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.0.0.70-10.0.0.75
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: node-metal-adv
  namespace: metallb-system
