all:
  children:
    k3s-workers:
      hosts:
        trahkube1:
          ansible_host: trahkube1.trahan.dev
          ansible_user: jtrahan
        trahkube2:
          ansible_host: trahkube2.trahan.dev
          ansible_user: jtrahan
        trahkube3:
          ansible_host: trahkube3.trahan.dev
          ansible_user: jtrahan
        trahkubeapi1:
          ansible_host: trahkubeapi1.trahan.dev
          ansible_user: jtrahan
        trahk3worker1:
          ansible_host: trahk3worker1.trahan.dev
          ansible_user: jtrahan
      vars:
        ansible_become: true
        ansible_become_method: sudo
        ansible_become_password: "{{ lookup('env', 'BECOME_PASSWORD') }}"
