virtual_ip: "10.0.1.64/23"
control_plane_virtual_ip: "10.0.0.65/23"

vrrp_servers:
- hostname: trahkubeapi1
  state: MASTER
  unicast_src_ip: 10.0.0.200
  virtual_router_id: 53
  vrrp_instance: "VI_K3_1"
  control_plane_vrrp_instance: "VI_K3_CP"
  interface: eth0
  priority: 255
  control_plane_priority: 250
  global_rt_id: k3s_node_4
  auth_pass: "{{ vrrp_auth_pass }}"
  is_control_plane: true
- hostname: trahkube1
  state: BACKUP
  unicast_src_ip: 10.0.0.210
  virtual_router_id: 53
  vrrp_instance: "VI_K3_1"
  control_plane_vrrp_instance: "VI_K3_CP"
  interface: eth0
  priority: 250
  control_plane_priority: 240
  global_rt_id: k3s_node_1
  auth_pass: "{{ vrrp_auth_pass }}"
  is_control_plane: true
- hostname: trahkube2
  state: BACKUP
  unicast_src_ip: 10.0.1.249
  virtual_router_id: 53
  vrrp_instance: "VI_K3_1"
  interface: eth0
  priority: 200
  global_rt_id: k3s_node_2
  auth_pass: "{{ vrrp_auth_pass }}"
  is_control_plane: false
- hostname: trahkube3
  state: BACKUP
  unicast_src_ip: 10.0.1.29
  virtual_router_id: 53
  vrrp_instance: "VI_K3_1"
  interface: eth0
  priority: 150
  global_rt_id: k3s_node_3
  auth_pass: "{{ vrrp_auth_pass }}"
  is_control_plane: false
- hostname: trahk3worker1
  state: BACKUP
  unicast_src_ip: 10.0.0.101
  virtual_router_id: 53
  vrrp_instance: "VI_K3_1"
  interface: eth0
  priority: 205
  global_rt_id: k3s_node_5
  auth_pass: "{{ vrrp_auth_pass }}"
  is_control_plane: false
