apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
  namespace: default
spec:
  insecureSkipVerify: true
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: proxmox1-service
#  namespace: default
#spec:
#  type: ClusterIP
#  ports:
#  - name: https
#    port: 8006
#    targetPort: 8006
#  selector:
#    app: proxmox1
#---
#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: proxmox1-service
#  namespace: default
#subsets:
#- addresses:
#  - ip: 10.0.0.50
#  ports:
#  - port: 8006
#---
#apiVersion: traefik.containo.us/v1alpha1
#kind: IngressRoute
#metadata:
#  name: prox1-trahan-ingress
#  namespace: default
#spec:
#  entryPoints:
#  - websecure
#  routes:
#  - match: Host(`vm1.trahan.dev`)
#    kind: Rule
#    services:
#    - name: proxmox1-service
#      kind: Service
#      port: 8006
#      serversTransport: insecure-transport
#  tls:
#    secretName: trahan-dev-cert
