apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingress
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`prometheus.trahan.dev`)
    kind: Rule
    services:
    - name: prometheus-server
      port: 80
  tls:
    secretName: trahan-dev-cert
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`grafana.trahan.dev`)
    kind: Rule
    services:
    - name: grafana
      port: 80
  tls:
    secretName: trahan-dev-cert
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-ingress
  namespace: cattle-system
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`rancher.trahan.dev`)
    kind: Rule
    services:
    - name: rancher
      port: 80
  tls:
    secretName: trahan-dev-cert
