apiVersion: v1
kind: Service
metadata:
  name: proxmox1-service
  namespace: default
spec:
  type: ExternalName
  externalName: proxmox1.trahan.dev
  ports:
  - name: https
    port: 8006
    targetPort: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: proxmox2-service
  namespace: default
spec:
  type: ExternalName
  externalName: proxmox2.trahan.dev
  ports:
  - name: https
    port: 8006
    targetPort: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: proxmox3-service
  namespace: default
spec:
  type: ExternalName
  externalName: proxmox3.trahan.dev
  ports:
  - name: https
    port: 8006
    targetPort: 8006
