version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: 4efpuy.jvmcdijzdrph90cu
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEFaMy9QZkZnYjNhMDYrTHVCeUNqZVhNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5UQXhNVGt3TURNMU5UbGFGdzB6TlRBeE1UY3dNRE0xTlRsYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBTmNNMFkxZ3hCZTA3TzZOYVpnazQ5YnRUR1pJSXI0bzc3S01mCjBvR1h5ZmlqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVS0Q2UTNLWnROZkxnRHV0bApDejYzZk9CMHRmZ3dCUVlESzJWd0EwRUFnVUlrcm9LOHdscWlzYnFJQVcrZGVtQklkb1NtR2NyZ0EyTG1pRnlnCjhqbERXMldPazQvL250ZGRpRkhoK2h6T3VIcXFFY09oLzhKYmp2cDU2VFVpQ0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJQjR3cUtuREVJUmtwd1laVEd4Y2hvbmMvTWRvYm1vTHZhOURVdldKK0tHTgotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.32.0
        extraMounts:
            - destination: /var/lib/longhorn
              type: bind
              source: /var/lib/longhorn
              options:
                - bind
                - rshared
                - rw
            - destination: /var/lib/longhorn
              type: bind
              source: /var/lib/longhorn
              options:
                - bind
                - rshared
                - rw
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network: {}
    install:
        disk: /dev/sda
        image: factory.talos.dev/installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b:v1.9.2
        wipe: false
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    nodeLabels:
        node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
    id: bVbBEbarN60q-jfb6G4pQRAZKB7P3YkL4s-I52Nv0pg=
    secret: W4hIJzn3KL1wqUKLr4sTUFYr0hXlRzqbioeh8OcIEzk=
    controlPlane:
        endpoint: https://10.0.0.71:6443
    clusterName: talos-proxmox-cluster
    network:
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: vuihiw.8plg2gdl7ir7gzxz
    secretboxEncryptionSecret: 20dr/vvgE4uEoIYvHIuDwf5KvINQccQTZ3feIjD2RGk=
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lRT1BMQUxxMjhZYkFNWmdQQmVMTnBlREFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNREV4T1RBd016VTFPVm9YRFRNMU1ERXhOekF3TXpVMQpPVm93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCTDc4cTlmQWlhb0ZvTnZQOUxDS2RVcHRRMjNTeElsblJkRkIvVTRaUTA5QTF1R3dtZHp0RkwxYkRNaTcKd0hNTjVvdUlIRDBGakFHMnRsSmZ6RjAzTm1hallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVmVDFKeUZtaVI0SThEN0hNK1pQaEl0bmJaQ0V3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQVBRNUpPRVkKRnJ2andWemZqalM3T3NLbkszMDk3b0FFSmF0Ni9xeVF5MGpHQWlCNXNsVzdZTmNNSi9mQ1FtZGlBeHlMaEVTTApuY0trUjR3M2d3a3VGcTIxV2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSURyUHJIbC9xTllzeFNuaTA0VXZNOENvemFTOEJJeU5kdVcyM1c0MFpTM1BvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFdnZ5cjE4Q0pxZ1dnMjgvMHNJcDFTbTFEYmRMRWlXZEYwVUg5VGhsRFQwRFc0YkNaM08wVQp2VnNNeUx2QWN3M21pNGdjUFFXTUFiYTJVbC9NWFRjMlpnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    aggregatorCA:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJYekNDQVFXZ0F3SUJBZ0lRQzlVUTFBQ2N3MjNybW41SE9FQVhlVEFLQmdncWhrak9QUVFEQWpBQU1CNFgKRFRJMU1ERXhPVEF3TXpVMU9Wb1hEVE0xTURFeE56QXdNelUxT1Zvd0FEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCREZMOWdYRjQzVE0zMFFSbkZCcjgzZnkzekpWMjJFT1NoaUgvcXZtZS9WYTQ4Y21HcjVzCnViUVU4R2dVanpJN2oybFJFRlk3YmZ1MEkxN3JBREtNSWcyallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVUrTjRDbEFoVDQyU05WaXpkbUltWUFpcG9qcjh3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloCkFJQ2o1WExtVHBWRWJaK1J3SmI1M216V1BKQWVwOFpQdFIwZjRXdG5tcFgwQWlCWS9odG4xdzFuNFh3ZDNkUHIKRUlDbTJ6bmZHakYxeWY0MlpmNzQ2LzFWZGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUVUWXdsS2ZkVTJDZ2hRKytXL0tHRzliQnVXMVF3ZjdCOU51OG9qcjFrb2hvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFTVV2MkJjWGpkTXpmUkJHY1VHdnpkL0xmTWxYYllRNUtHSWYrcStaNzlWcmp4eVlhdm15NQp0QlR3YUJTUE1qdVBhVkVRVmp0dCs3UWpYdXNBTW93aURRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    serviceAccount:
        key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBeXBOUWpzZEZUYWNZSjlpQUwremtmUWJFWlRESzNlRDZUNnlES1Q3ZW5Xa1VZbGxDCkVoelZOUjljK1krbEFLUEZvMEpadVdaNE1iSGtHanNacTdRV0NwVkdWdkpuZlRpeTBMNlNVUmpNeWw2MkppaWkKNUEvdkpRblRtVEllNnB4a2FKS05ZMFFUNk5VNmV2MmgweVNOWG9MeHNhZnNCUEx1SkJGV3FrZ0R0eU5HTkUrWgptMzBFaWJJNUZCZUFjdkFQR0N1OFpWT2ZmcUJQRVBrOUpqamV5WmJDMkxZeUVxV0VMb01rc1paZi8xMkVFS0N2CmkwNnh4eFpQeGtVdS92ZElsREhsbkxQNGNSMTFtdHhsS3EyY1p3VkFTVDc0SGlrQ2V0SjJ5a0VIcWY1Y3oybjUKdmV4cDBXTy9pOHNvUTBBM2dkbkVsTFYvRlFnb2xDK1FqY3Y3dVNOcHh0TGZpL0V3MTFVSU95RGwxanJIZEdmRQpUMWhWdmZERVZzRXBMSnFWY3UwcW50enlzS0FPWlF1Z216S1BWNWhJQmVqSHdRajdQUzRCNHVMTFFkczJnMTg2Ck1lbGtCMFM1eERLMm5CT3ZCMFlpcUo2UTBwdHAzdklZRzZtRDhMYkt3bm02RnRDWCt4N0I0RjRmRkpoT0ZraWIKTVlRTmhCNEltU3Yxa2VJdmJmSW9ycjdxMTlSVlIyQUJ2TUpJZVQxazV3Vk5RWTJqOU1yTmwrcVZmaWRtSDVwbwphN0Z5U04yaEtyK3RJSG9KS2dZazNwOFh5V0w5VWRUc1cxaUc3dTZVMkZGR3FpNzVlWWVFQTliUVB5Q1E2L1ZyCmR1Qm01c00xc0lrU0tKSzJnVVJyL09uSXN3MVNmd3NMZ1dIbjlKM0xYSlVZK3A5UXJXOElKTENNODVzQ0F3RUEKQVFLQ0FnQVB2VXB4RFlLUStmNmllZXZieldnalhyYzd0WUxOb29GUVYzTUpiVjBXbGVlRGpMUFpmR3dFYUo5cwp0SUI1Z0VBRzQwemRYdHpQMzZaOWMwSVhXVEt0TjlQelJYcE0vRzdJVVVaRkRzdzZuUWxDQmI1Q1FncXVzZ2pDCnltWWtqR293eGRJK2VEZWp5NDF6cU9rOTRvVXBacnNvdG9kY0N4UDlzV3N1WjlJQ0ZMZUxzUE9hWlNoSkdwUGMKdjhhM0ozZkV4UUVxVGtrQ0thcDdBeUtCS2NJRm43VWI2V3dTanRHcVczNHFYaWl2U3JETUtlLzV2dStKTEc2ZQpWUm5GcmFqeCtyNkFZbXRYUHBhNHBZOG10YjZGTXA5QUVhaHRqM29sMk54cDhvdUo1YjJJVUErYmRoYnlzZkZjCkJ6amxvTU92VHlBNi9hOFdEMEEzNDBveitqbGdrY0NVSW14akJ4YWNadWxTY1VTUGtCajdwcG1VUkRZVURvckgKdm1ZaENNVzNxZkRtZjNBS2NySUFjUHVXdzR6MFJjdkJvQi94emg3dFhZd1hacTZFUDQxeHlJK1hHSFZmUFpZLwp1T3BpVlozRGt3YzQ3L05kVk9RTThLb2Q0NFZFSysydkpwVHJOUEsvUzVoQWVDUGs3dmYyandnNUZYWm4xSzRuCit1WCtzRHpLZGU5Sk5iS2lyK1dMek9PYjUrYlVCZytwaFppSUg4anlaOHFwdWxuOU9OVVhTVndyQ0czOG41bjgKRGkrV0V1YjNKTGc1bldUNGlWZkdxMUprdW9TcVp1dVp0c2RMRU04ZkgzQmowUDd3bDd4bVptb1FNTWQ1N3BqRgorMjY4aHdYWEVCKzdFc09WMXFreVJ4U0RucWhteVpKemJtYTNQclZRbmpqT20xVHpnUUtDQVFFQTQ5dXRSTmxoCnFSak43cnZLOEd5bDMrS0lQRzRqYjdnTU9CbTdvS2xqT09DUE84ZFdnQmRNMVRSdFFwVWtWbDFZMWlJay91ZWoKWmRBb1UxWURLVzc5RXl5Ky9rRkZXUWxqM3hBU1p6U1RlTVB0cTFYbHVSZDNyTVE2a3R4STFwUjRUL2YrMWQ3eQpPb1BwaEV6dUNHWHhhRzlRa3B5UHNDbGpFd0RuMGw0WVBDWWdaTUQwYTJ1SnpWbmFUdk1UVHR3LzlJVDdlU1A0CnU3aTk2Y213TExDQlB1c2d4bTNKMnVtTmNYamd2K0czaklJOE1hYW5UTWZYVURmVmFTbDZyaFh2UE1VL3ZVcCsKMVBPeDdtd0FJSzBPQzZ4OS80dEpyUmV3RGl1Sk1ra0RTWkM2RjVheVNmWG5tSzRlbDNmL0prQkxIcm1IM1dwQQpoYmNDalg5VEkwWnFpd0tDQVFFQTQ1aEMxSlY1OFluaWdzU2d1YXh0ZE04RDY0YXhqTXZ2Qm96dDY3ZUZFQjl6ClM1cGNxQ1JMVWw2OHRvckY3NFBhQlJ6YnNPS2lEdXZDeUJqU2cxNkkyYVpiVGN4L2tMdVZYMXFZc3hHb0U4WTkKS05ZMitQY3QzMzY4M3NkQ0pxS3FhbG1NSDRkbFB4cmsxMm11aTJZSGZnMk5RSjBYeWR5ZmxLNzVmZVEzTEdXcwpWWnpjZHJLUTNiNjFpbzBkRzVzVmNiYTNNc1VNNEZnWnJxL0U1b2ZtY2JjZVJ3a1hjNHF3cnpHT2tNNDJVNklzCi9jQVBPS1NDOHk3Y2w0d3RDYkZOOFhWNHIwaXlGVlpza250bExObE82VFFvcEFFNklRYXVkVnNxOHMyU1pQczkKdWFuazhZbVFhNlFnNDluQ0JmWFJOd09Bblc1K1RVRTNySkxVOXF5Tk1RS0NBUUJLSnlPc1ZGSkVCWjUvSXY1WQpZQU5iYVEyTkhRckxRTW81TjZhb0VuZ0grb3lpbDZ5KzR0Wk9URkdDYWFiNXRFZEU2TGZCZlFEZ0VXNE9NTisyCmpEZ3dGVS9TenNzU3ZzdVJ2RmxBM1F0aE1lSVc4RTFpZnhDaldQajI4bG1CKzY5cjF2bElBTll6MU5vYUJDOHkKN0hvejBvWVdNSDFTaHlXRytiUjM4Y2RSUzljZTh1eVlTTmIvelU0T2cyeTFMVmhpNnlRcnVGa3FQbVVQd0dObApKOHZuL2YwY2xuNHFqL2RJQmw2ZUU0YjRZeW5UdnJpVGREWE9GVjJPYThGUkJqSmxSSXdKdmtTb2FPWnZBUmJKCmk0Z1dwSHdjdmVlc1BSaytnMHlTNE5BQkVPaCs1THdBOWRYNUNqRktlZksvTUExQ1luNmt2LzlmaEw5LzdQL1IKYXdraEFvSUJBRjBZTCtYeXluR0JQQlRQUndzTHU2MzI2NXlRZU5tbHBUemhzb1FqaWhzaE1qRHZrQXo2NDVCcQp6ZmhBNVZ2bWEreUJkRjl6SkdURURPVjZPY21naG91NG4wcEFac0dWNlRDYXh6RWYvTWN4NUZ4cTJ3dVZWNzgrCmdSVURIa3pkWnFXZndWQTRPckxJVm1qQ2dySGtaeFlwaHVpeUdVUHBxYURRdlo3QUZjMWtQVXk3bi9ZeGJrNDEKcnQ1Z2dGS0ZhZzBjZHUwZWF2anRNSHdpeTRDY2dDZHRoc1g1c3cwQTR1cVdjOEZKaURGSGVlM0ZmTFJubm1USQplMVRGOHJvdk96bVVHbXhnYU8rUGJWT3hnNTRIdVY1c2hsOG5YVmFhL0F0bTRqZDAzUGZQU04xRDRERG9XeG1jCmhoT05RKzdhTU55MjR3b0NZMGxJYnZSNUR3RmpiVkVDZ2dFQkFKWkt3YTRyelFEVTZpam8xK3dyY1FJM1FaSzcKblU3ZmliZEFZME5ubGc2MTJ6MWkwRXYwVS9qQitHaEZkWHhIU3ZUT1ZDN3ZmSUEzalpVZC9DcTV5aU03UFVIbwprNS9PUHh0dmdBbEViTitKWG5wcWN1QlNHSkR3ckpRVDVKelExVndTdmlMM3F0RS82ZnppSG9kZG9OTkNHcG1TCkdkcFVWT3NWMEw5d0dOdXh0aUEwRmRqSDhXUDhlbWxLenRhOXgvQ0M1Z2Frb1JYTU04S1VobWtnOHp3MmJ0VDcKRGJDbUthc0grSlpXNlBjV2dJQk5QaFdlTnVMSkRSYjk5aVl1OFN6UUVweFY1U3dycVo5RHRXbzYxdXNZSDhnYQozVlp1eFpMRSs3a2haVWdyNFBFK0tVN1hlajN0QVBaaWp0bTUvZlpvVFVlQUpWVVhFL3lmTUtlT3FOQT0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.32.0
        certSANs:
            - 10.0.0.71
        disablePodSecurityPolicy: true
        admissionControl:
            - name: PodSecurity
              configuration:
                apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                defaults:
                    audit: restricted
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                exemptions:
                    namespaces:
                        - kube-system
                    runtimeClasses: []
                    usernames: []
                kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: Metadata
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.32.0
    proxy:
        image: registry.k8s.io/kube-proxy:v1.32.0
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.32.0
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmVENDQVNTZ0F3SUJBZ0lSQU9HVFJtMklkaGhhWTFlandUeU5KOVF3Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FWlhSalpEQWVGdzB5TlRBeE1Ua3dNRE0xTlRsYUZ3MHpOVEF4TVRjd01ETTFOVGxhTUE4eApEVEFMQmdOVkJBb1RCR1YwWTJRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUK2NCN3N5OTBWCkg3QTdOR1EvTDhKZzNxTkFDL0pDN3p3NFg4K1ZRZFcvb1l6RlpBNnEzSVBXTk9SUHJkTUtvVjRwNStpSXBJZHUKbHRxeCtRV1lkZnUzbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSApBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkxlUU1JN2EyaU9TCjZ6b2Ftems0TURNcWtTVThNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJQllxOUFaZWVjWlhiT0o1aTJqUDhoY2EKNlIyWVpzcFAyQ1pQeXNXZy9MczFBaUErd0ppVTFocUFIem4yTjdiQUtSOVBMaW84M0t4cldHVzd0OHRxU2ExZwoxUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUZWQkV4aHJGK3h1blMvNG4xWG9nY0ExYlNaTkVHaGJjcXJOMFMyOHVyZFVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFL25BZTdNdmRGUit3T3pSa1B5L0NZTjZqUUF2eVF1ODhPRi9QbFVIVnY2R014V1FPcXR5RAoxalRrVDYzVENxRmVLZWZvaUtTSGJwYmFzZmtGbUhYN3R3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
