version: v1alpha1
debug: false
persist: true
machine:
    type: worker
    token: 4efpuy.jvmcdijzdrph90cu
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEFaMy9QZkZnYjNhMDYrTHVCeUNqZVhNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5UQXhNVGt3TURNMU5UbGFGdzB6TlRBeE1UY3dNRE0xTlRsYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBTmNNMFkxZ3hCZTA3TzZOYVpnazQ5YnRUR1pJSXI0bzc3S01mCjBvR1h5ZmlqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVS0Q2UTNLWnROZkxnRHV0bApDejYzZk9CMHRmZ3dCUVlESzJWd0EwRUFnVUlrcm9LOHdscWlzYnFJQVcrZGVtQklkb1NtR2NyZ0EyTG1pRnlnCjhqbERXMldPazQvL250ZGRpRkhoK2h6T3VIcXFFY09oLzhKYmp2cDU2VFVpQ0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: ""
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.32.0
        extraMounts:
            - destination: /var/lib/longhorn
              type: bind
              source: /var/lib/longhorn
              options:
                - bind
                - rshared
                - rw
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network: {}
    install:
        disk: /dev/sda
        image: factory.talos.dev/installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b:v1.9.2
        wipe: false
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
cluster:
    id: bVbBEbarN60q-jfb6G4pQRAZKB7P3YkL4s-I52Nv0pg=
    secret: W4hIJzn3KL1wqUKLr4sTUFYr0hXlRzqbioeh8OcIEzk=
    controlPlane:
        endpoint: https://10.0.0.71:6443
    clusterName: talos-proxmox-cluster
    network:
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: vuihiw.8plg2gdl7ir7gzxz
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lRT1BMQUxxMjhZYkFNWmdQQmVMTnBlREFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNREV4T1RBd016VTFPVm9YRFRNMU1ERXhOekF3TXpVMQpPVm93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCTDc4cTlmQWlhb0ZvTnZQOUxDS2RVcHRRMjNTeElsblJkRkIvVTRaUTA5QTF1R3dtZHp0RkwxYkRNaTcKd0hNTjVvdUlIRDBGakFHMnRsSmZ6RjAzTm1hallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVmVDFKeUZtaVI0SThEN0hNK1pQaEl0bmJaQ0V3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQVBRNUpPRVkKRnJ2andWemZqalM3T3NLbkszMDk3b0FFSmF0Ni9xeVF5MGpHQWlCNXNsVzdZTmNNSi9mQ1FtZGlBeHlMaEVTTApuY0trUjR3M2d3a3VGcTIxV2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: ""
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
