version: "3"
services:
  reverse:
    container_name: homelab-nginx2
    image: nginx
    hostname: homelab-nginx2
    restart: unless-stopped
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/:/etc/nginx/certs:ro
    networks:
      - bridgehomelab
networks:
  bridgehomelab:
    driver: bridge
    name: lab-bridge
