version: "3.8"
services:
  reverse:
    container_name: nginx-cluster
    image: nginx
    hostname: nginx-cluster
    restart: unless-stopped
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/:/etc/nginx/certs:ro
    networks:
      - bridgehomelab
    ports:
      - "80:80"
      - "443:443"
networks:
  bridgehomelab:
    external: true
    name: lab-bridge
