data_directory = '/db/dev/postgresql/14/main'		# use data in another directory
hba_file = '/etc/postgresql/14/main/pg_hba.conf'	# host-based authentication file
ident_file = '/etc/postgresql/14/main/pg_ident.conf'	# ident configuration file
external_pid_file = '/var/run/postgresql/14-main.pid'			# write an extra PID file
listen_addresses = '*'		# what IP address(es) to listen on;
port = 5432				# (change requires restart)
max_connections = 100			# (change requires restart)
unix_socket_directories = '/var/run/postgresql'	# comma-separated list of directories
ssl = on
ssl_cert_file = '/etc/ssl/certs/ssl-cert-snakeoil.pem'
ssl_key_file = '/etc/ssl/private/ssl-cert-snakeoil.key'
shared_buffers = 128MB			# min 128kB
dynamic_shared_memory_type = posix	# the default is the first option
wal_level = replica			# minimal, replica, or logical
max_wal_size = 1GB
min_wal_size = 80MB
archive_mode = on		# enables archiving; off, on, or always
archive_command = 'test ! -f /mnt/backups/pg_archive/%f && cp %p /mnt/backups/pg_archive/%f'
max_wal_senders = 5		# max number of walsender processes
hot_standby = on		# (change requires restart)
log_line_prefix = '%m [%p] %q%u@%d '		# special values:
log_timezone = 'Etc/UTC'
cluster_name = '14/main'			# added to process titles if nonempty
stats_temp_directory = '/var/run/postgresql/14-main.pg_stat_tmp'
datestyle = 'iso, mdy'
timezone = 'Etc/UTC'
lc_messages = 'C'			# locale for system error message
lc_monetary = 'C'			# locale for monetary formatting
lc_numeric = 'C'			# locale for number formatting
lc_time = 'C'				# locale for time formatting
default_text_search_config = 'pg_catalog.english'
include_dir = 'conf.d'
