version: "3"

networks:
  ovnet1:
    external: true

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - ovnet1

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - ovnet1
