- name: install docker
  hosts: utility-gui
  remote_user: jtrahan
  become: true

  tasks:
    - name: Docker Pre-reqs
      ansible.builtin.command: apt update 
        become: yes
    - name: Docker Pre-reqs
      ansible.builtin.command: apt -y install apt-transport-https ca-certificates curl software-properties-common
        become: yes
    - name: installing docker.io version compatible with portainer
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - docker.io=24.0.5-0ubuntu1~22.04.1
    - name: add jtrahan to docker group
      user:
        name: jtrahan
        groups: docker
        append: yes
