- name: Resize partition
  hosts: "{{ ansible_limit | default(omit) }}"
  remote_user: jtrahan
  become: true
  vars:

  tasks:
    - name: Extend an existing partition to fill all available space
      community.general.parted:
        device: "/dev/vdb"
        number: 1
        part_end: "100%"
        label: gpt
        resize: true
        state: present
