services:
  git-repo:
    image: gitea/gitea:1.21.10
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db.trahan.dev:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=svc-gitea
      - GITEA__database__PASSWD=giteadb!
    restart: unless-stopped
    networks:
      - ovnet1
    volumes:
      - /mnt/trahan-nas/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
networks:
  ovnet1:
    external: true
    name: ovnet1
