domain: trahan.dev
forward_zones: ['trahan.dev']
reverse_zones: ['1.0.10.in-addr.arpa', '0.0.10.in-addr.arpa']
forwarders: ['1.1.1.1', '8.8.8.8', '9.9.9.9']
acl_allow_transfer: ['10.0.0.14', '10.0.0.15', '10.0.0.17', '10.0.0.64', '10.0.1.64', '127.0.0.0/8']

nameservers:
- {name: trah-dns-01, zone: trahan.dev, ip_address: '10.0.0.15', last: 15}
- {name: trahdns2, zone: trahan.dev, ip_address: '10.0.0.14', last: 14}
- {name: trahdns3, zone: trahan.dev, ip_address: '10.0.0.17', last: 17}

dns_records:
- {host: vm1, type: A, zone: trahan.dev, ip_address: '10.0.1.64'}
- {host: proxmox1, type: A, zone: trahan.dev, ip_address: '10.0.0.50'}
- {host: vm2, type: A, zone: trahan.dev, ip_address: '10.0.1.64'}
- {host: proxmox2, type: A, zone: trahan.dev, ip_address: '10.0.0.9'}
- {host: vm3, type: A, zone: trahan.dev, ip_address: '10.0.1.64'}
- {host: proxmox3, type: A, zone: trahan.dev, ip_address: '10.0.0.7'}
- {host: trahan-nas, type: A, zone: trahan.dev, ip_address: '10.0.0.8'}
- {host: trahan-nas, type: PTR, zone: 0.0.10.in-addr.arpa., ip_suffix: '8'}
- {host: trahdb1, type: PTR, zone: 1.0.10.in-addr.arpa., ip_suffix: '109'}
- {host: trah-dns-01, type: PTR, zone: 0.0.10.in-addr.arpa., ip_suffix: '14'}
- {host: trahdns2, type: PTR, zone: 0.0.10.in-addr.arpa., ip_suffix: '14'}
- {host: trahdns3, type: PTR, zone: 0.0.10.in-addr.arpa., ip_suffix: '17'}


---
# vars file for Bind setup

records:
  ns1:
    forward: 10.0.0.15
    type: A
    last: 15
    rev: 30.1.10.in-addr.arpa.
  ansible:
    forward: 10.1.30.5
    type: A
    last: 5
    rev: 30.1.10.in-addr.arpa.


