---
cluster:
  apiServer:
    admissionControl:
      - name: PodSecurity
        configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1alpha1
          defaults:
              audit: privileged
              audit-version: latest
              enforce: privileged
              enforce-version: latest
              warn: privileged
              warn-version: latest
          exemptions:
              namespaces:
                  - kube-system
              runtimeClasses: []
              usernames: []
          kind: PodSecurityConfiguration