- name: Add Docker Repository
  hosts: "{{ ansible_limit | default(omit) }}"
  become: yes
  tasks:
  - name: Install required packages for adding repositories
    ansible.builtin.apt:
      pkg:
      - ca-certificates
      - curl
      state: present
      update_cache: yes

  - name: Create APT keyrings directory
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Add Docker's official GPG key
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: '0644'
      validate_certs: yes
    register: gpg_key

  - name: Ensure the GPG key was added
    ansible.builtin.stat:
      path: /etc/apt/keyrings/docker.asc
    register: gpg_key_stat

  - name: Add Docker repository to APT sources
    ansible.builtin.lineinfile:
      path: /etc/apt/sources.list.d/docker.list
      line: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      create: yes
    when: gpg_key.stat.exists

  - name: Update APT package cache
    ansible.builtin.apt:
      update_cache: yes
