---
- name: Install Dev Applications and create users
  # pass --limit=<hostname>
  hosts: "{{ ansible_limit | default(omit) }}"

  vars_files:
    - vars.yml
    #- devops_vars.yml
    - vault.yml


  handlers:
  - name: Restart sshd
    ansible.builtin.systemd:
      name: sshd
      state: restarted
    become: yes

  tasks:

    - name: Ensure required groups are present
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop: "{{ dev_server_users | map(attribute='groups') | flatten | unique }}"
      become: yes

    - name: Create users
      ansible.builtin.user:
        user: "{{ item.username }}"
        comment: "{{ item.description }}"
        state: present
        uid: "{{ item.uid }}"
        create_home: yes
        generate_ssh_key: true
        groups: "{{ item.groups }}"
        password: "{{ (user_pw | selectattr('user', 'equalto', item.username) | map(attribute='password') | first) }}"
        shell: "{{ item.shell }}"
      loop: "{{ dev_server_users }}"
      become: yes

    - name: Ensure each user has their SSH keys added to authorized_keys
      ansible.builtin.authorized_key:
        user: "{{ item.user }}"
        key: "{{ item.auth_keys | join('\n') }}"
      loop: "{{ ssh_keys }}"
      become: yes

    - name: Run apt cache update
      ansible.builtin.apt:
        update_cache: yes
      become: yes

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg: "{{ apt_packages }}"
        state: present
      become: yes

    - name: Configure sudoers settings for users.
      community.general.sudoers:
        name: "{{ item.username }}-sudoers-config"
        state: present
        user: "{{ item.username }}"
        commands: ALL
        sudoers_path: /etc/sudoers.d
        nopassword: "{{ item.nopw_sudo }}"
      loop: "{{ dev_server_users }}"
      become: yes

    - name: Create Directory for build repos
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/build'
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      become: yes
      become_user: jtrahan

    - name: Create Directory to Neovim build from source
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/build/neovim'
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      become: yes
      become_user: jtrahan
      register: nvim_repo_dir

    - name: Clone Neovim repo
      ansible.builtin.git:
        repo: https://github.com/neovim/neovim.git
        dest: '{{ nvim_repo_dir.path }}'
        clone: yes
      become: yes
      become_user: jtrahan

    - name: Make build for Neovim
      ansible.builtin.command:
        cmd: make CMAKE_BUILD_TYPE=RelWithDebInfo
        chdir: '{{ ansible_env.HOME }}/build/neovim'
        creates: '{{ ansible_env.HOME }}/build/neovim/build/bin/nvim'
      become: yes
      become_user: jtrahan

    - name: Make Install Neovim
      ansible.builtin.command:
        cmd: make Install
        chdir: '{{ nvim_repo_dir.path }}'
        creates: '/usr/local/bin/nvim'
      become: yes





