all:
  children:
    k3s-workers:
      hosts:
        trahkube1:
          ansible_host: trahkube1.trahan.dev
          ansible_user: jtrahan
        trahkube2:
          ansible_host: trahkube2.trahan.dev
          ansible_user: jtrahan
        trahkube3:
          ansible_host: trahkube3.trahan.dev
          ansible_user: jtrahan
      vars:
        ansible_become: true
        ansible_become_method: sudo
        ansible_become_password: "{{ lookup('env', 'BECOME_PASSWORD') }}"
    dns-servers:
      hosts:
        trahdns1:
          ansible_host: 10.0.0.15
          ansible_user: devops
        trahdns2:
          ansible_host: 10.0.0.14
          ansible_user: devops
        trahdns3:
          ansible_host: 10.0.0.17
          ansible_user: devops
      vars:
        ansible_become: true
        ansible_become_method: sudo
        ansible_become_password: "{{ lookup('env', 'ANSIBLE_DEVOPS') }}"
    tailscale-routers:
      hosts:
        trah-rt-03:
          ansible_host: 10.0.0.85
          ansible_user: jtrahan
      vars:
        ansible_become: true
        ansible_become_method: sudo
        ansible_become_password: "{{ lookup('env', 'ANSIBLE_JT') }}"
