---
- name: Install Bind
  hosts: dns-servers

  vars_files:
    - vars.yml
  become: yes

  handlers:
  - name: Restart bind9
    ansible.builtin.systemd:
      name: bind9
      state: restarted
    become: true

  tasks:
  - name: Ensure dependencies are installed.
    apt:
      name:
        - bind9
        - bind9utils
        - bind9-doc
      state: present

