---
apiVersion: v1
kind: Service
metadata:
  name: s2pg-svc
  namespace: development
spec:
  ports:
    - name: svc3-webport
      port: 5432
      targetPort: 5432
  selector:
    app: webpod
  type: LoadBalancer
