- name: install Postgres and setup standby replica
  hosts: "{{ ansible_limit | default(omit) }}"
  vars_files:
    - vault.yml
    - vars.yml

  handlers:
    - name: Restart postgresql
      ansible.builtin.systemd:
        name: postgresql
        state: restarted
      become: true

  tasks:
    - name: Install PostgreSQL and psycopg2
      ansible.builtin.apt:
        name: postgresql,postgresql-contrib,python3-psycopg2
        state: present
        update_cache: true
      become: true

    - name: Start and enable the service
      ansible.builtin.systemd:
        name: postgresql
        state: started
        enabled: true
      become: true

    - name: Add entries to pg_hba
      community.postgresql.postgresql_pg_hba:
        create: true
        dest: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
        address: "{{ item.address | default(omit) }}"
        contype: "{{ item.contype }}"
        databases: "{{ item.databases }}"
        method: "{{ item.method }}"
        users: "{{ item.users }}"
      become: true
      become_user: postgres
      with_items: "{{ postgres_hba_standy_entries }}"
      notify:
        - Restart postgresql

    - name: Stop postgresql
      ansible.builtin.systemd:
        name: postgresql
        state: stopped
      become: true

    - name: Remove all files and directories inside main, but keep main directory
      ansible.builtin.command:
        cmd: |
          find /var/lib/postgresql/{{ pg_version }}/main/ -mindepth 1 -delete
      become: true
      become_user: postgres


    - name: Init streaming replica
      ansible.builtin.command:
        cmd: pg_basebackup -h "{{ item.hostname }}" -D /var/lib/postgresql/{{ pg_version }}/main -U replicator -v -R -X stream
      become: true
      become_user: postgres
      notify:
        - Restart postgresql
      with_items: "{{ primary_pg_server }}"



