- hosts: test-db

  vars_files:
    - vault.yml
    - vars.yml

  handlers:
    - name: Restart postgresql
      ansible.builtin.systemd:
        name: postgresql
        state: restarted
      become: true  

  tasks:
    - name: Install PostgreSQL and psycopg2
      ansible.builtin.apt:
        name: postgresql,postgresql-contrib,python3-psycopg2,p7zip-full
        state: present
        update_cache: true
      become: true

    - name: Start and enable the service
      ansible.builtin.systemd:
        name: postgresql
        state: started
        enabled: true
      become: true

    - name: Set options
      community.postgresql.postgresql_set:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      become: yes
      become_method: sudo
      become_user: postgres
      vars:
        allow_world_readable_tmpfiles: true
      with_items: "{{ postgresql_options }}"
      notify:
        - Restart postgresql

    - name: Create the databases
      community.postgresql.postgresql_db:
        name: "{{ item }}"
        encoding: "UTF-8"
      become: true
      become_user: postgres
      with_items: "{{ postgresql_databases }}"

    - name: Create the users
      community.postgresql.postgresql_user:
        db: "{{ item.db }}"
        name: "{{ item.name }}"
        password: "{{ item.password | default(omit) }}"
      become: true
      become_user: postgres
      environment:
        PGOPTIONS: "-c password_encryption=scram-sha-256"
      with_items: "{{ postgresql_users }}"

    - name: Create the schemas
      community.postgresql.postgresql_schema:
        db: "{{ item.db }}"
        name: "{{ item.name }}"
        owner: "{{ item.name }}"
      become: true
      become_user: postgres
      with_items: "{{ postgresql_schemas }}"

    - name: Set the user privileges
      community.postgresql.postgresql_privs:
        database: "{{ item.db }}"
        state: present
        objs: "{{ item.objs | default(omit) }}"
        privs: "{{ item.privs }}"
        type: "{{ item.type | default(omit) }}"
        roles: "{{ item.roles | default(omit) }}"
      become: true
      become_user: postgres
      with_items: "{{ postgresql_privs | default([]) }}"

    - name: Add entries to pg_hba
      community.postgresql.postgresql_pg_hba:
        dest: "/etc/postgresql/14/main/pg_hba.conf"
        address: "{{ item.address | default(omit) }}"
        contype: "{{ item.contype }}"
        databases: "{{ item.databases }}"
        method: "{{ item.method }}"
        users: "{{ item.users }}"
      become: true
      become_user: postgres
      with_items: "{{ postgresql_hba_entries }}"
      notify:
        - Restart postgresql

    - name: Enable the HSTORE extension
      community.postgresql.postgresql_ext:
        name: "{{ item.name }}"
        db: "{{ item.db }}"
        state: present
      become: true
      become_user: postgres
      with_items: "{{ postgresql_extensions }}"
      notify:
        - Restart postgresql
    - name: Grant REPLICATION to user
      community.postgresql.postgresql_query:
        db: infradb-dev
        query: 
          - ALTER USER replicator REPLICATION;
          - ALTER USER jtrahan REPLICATION;
      become_user: postgres
      become: true
      notify:
        - Restart postgresql

    - name: Grant REPLICATION to user
      community.postgresql.postgresql_query:
        db: infradb-dev
        query: 
          - ALTER USER replicator REPLICATION;
          - ALTER USER jtrahan REPLICATION;
      become_user: postgres
      become: true
      notify:
        - Restart postgresql

    - name: Install bottle python package
      ansible.builtin.pip:
        name: b2
        state: present

    - name: Create directory for pg backups
      ansible.builtin.file:
        path: /pgdumps
        state: directory
        mode: "0775"
        owner: postgres
      become: true

    - name: Ensure group "pgbackup" exists
      ansible.builtin.group:
        name: pgbackup
        state: present
        gid: 1900
      become: true

    - name: Create directory for pg backups
      ansible.builtin.file:
        path: /pgdumps/venv
        state: directory
        mode: "0775"
        owner: postgres
        group: pgbackup
      become: true

    - name: Add users to pgbackup
      ansible.builtin.user:
        name: jtrahan
        groups:
          - postgres
          - jtrahan
          - pgbackup
        append: true
      become: true
    
    - name: Add postgres user to the pgbackup groups
      ansible.builtin.user:
        name: postgres
        groups:
          - pgbackup
        append: true
      become: true

    - name: Download backup from b2 for go-infra
      ansible.builtin.command: /usr/local/bin/b2 account authorize "{{ item.key }}" "{{ item.secret }}"
      with_items: "{{ b2_app_key_and_secret }}"

    - name: Download backup from b2 for go-infra
      ansible.builtin.command: 
        cmd: /usr/local/bin/b2 file download "{{ item.remotefile }}" "{{ item.localfile }}"
        creates: "{{ item.localfile }}"
      with_items: "{{ b2_app_key_and_secret }}"

    - name: Unarchive a file with extra options
      ansible.builtin.command: 
        cmd: 7z x {{ item.localfile }} "-p{{ item.pw }}"
        chdir: /pgdumps
        creates: /pgdumps/go-infra.sql
      with_items: "{{ seven_z_pw }}"

    - name: Create the databases
      community.postgresql.postgresql_db:
        name: "{{ item.db_name }}"
        state: restore
        target: "/pgdumps/{{ item.db_name }}.sql"
        encoding: "UTF-8"
      become: true
      become_user: postgres
      with_items: "{{ seven_z_pw }}"

    




