local_7zip_dir: /pgdumps/7z_backups
postgresql_options:
- { name: listen_addresses, value: '0.0.0.0' }
- { name: wal_level, value: replica }
- { name: max_wal_senders, value: 5 }
- { name: archive_mode, value: on }
- {
    name: archive_command,
    value: 'test ! -f /mnt/backups/pg_archive/%f && cp %p /mnt/backups/pg_archive/%f'
  }

postgresql_databases: [ infradb-dev, automation-db, go-infra, k3s ]

postgresql_users:
- {
    db: infradb-dev,
    name: jtrahan,
    password: "{{ vault_postgresql_jtrahan_password }}"
  }
- {
    db: k3s,
    name: k3suser,
    password: "{{ vault_postgresql_jtrahan_password }}"
  }
- {
    db: automation-db,
    name: replicator,
    password: "{{ vault_postgresql_replicator_password }}"
  }

postgresql_schemas:
- { db: infradb-dev, name: jtrahan, owner: jtrahan }
- { db: go-infra, name: jtrahan, owner: jtrahan }
- { db: k3s, name: k3suser, owner: k3suser }
- { db: automation-db, name: replicator, owner: replicator }

postgresql_privs:
- { db: infradb-dev, roles: jtrahan, privs: ALL, type: database }
- { db: go-infra, roles: jtrahan, privs: ALL, type: database }
- { db: k3s, roles: k3suser, privs: ALL, type: database }
- { db: k3s, roles: jtrahan, privs: ALL, type: database }
- { db: automation-db, roles: replicator, privs: ALL, type: database }

postgresql_hba_entries:
- { contype: local, databases: all, users: all, method: peer }
- {
    contype: host,
    databases: all,
    users: jtrahan,
    address: samenet,
    method: scram-sha-256
  }
- {
    contype: host,
    databases: all,
    users: k3s,
    address: samenet,
    method: scram-sha-256
  }
- {
    contype: host,
    databases: replication,
    users: replicator,
    address: samenet,
    method: trust
  }
- {
    contype: host,
    databases: all,
    users: replicator,
    address: db1.trahan.dev,
    method: trust
  }
- {
    contype: host,
    databases: all,
    users: replicator,
    address: db2.trahan.dev,
    method: trust
  }
- {
    contype: host,
    databases: all,
    users: replicator,
    address: db3.trahan.dev,
    method: trust
  }
- {
    contype: host,
    databases: all,
    users: replicator,
    address: db4.trahan.dev,
    method: trust
  }
- {
    contype: host,
    databases: all,
    users: replicator,
    address: db5.trahan.dev,
    method: trust
  }
- { contype: host, databases: all, users: all, method: scram-sha-256 }

postgres_hba_standy_entries:
- { contype: local, databases: all, users: all, method: peer }
- {
    contype: host,
    databases: replication,
    users: replicator,
    address: samenet,
    method: trust
  }
- {
    contype: host,
    databases: all,
    users: replicator,
    address: pgprime.trahan.dev,
    method: trust
  }
- {
    contype: host,
    databases: all,
    users: replicator,
    address: db5.trahan.dev,
    method: trust
  }
- {
    contype: host,
    databases: all,
    users: replicator,
    address: db3.trahan.dev,
    method: trust
  }
- {
    contype: host,
    databases: all,
    users: replicator,
    address: db5.trahan.dev,
    method: trust
  }
- {
    contype: host,
    databases: all,
    users: replicator,
    address: 10.0.0.28,
    method: trust
  }
- {
    contype: host,
    databases: all,
    users: replicator,
    address: 10.0.0.29,
    method: trust
  }
- {
    contype: host,
    databases: all,
    users: all,
    address: all,
    method: scram-sha-256
  }

postgresql_extensions:
- { db: infradb-dev, name: hstore }

b2_app_key_and_secret:
- {
    key: "{{ vault_b2_app_key }}",
    secret: "{{ vault_b2_app_secret }}",
    localfile: /pgdumps/goinfradb.7z,
    remotefile: 'b2://trahan-postgres-backups/goinfra.7z',
    archive_dir_b2: 'b2://trahan-postgres-backups/7z_backups',
    local_archive_dir: /pgdumps/7z_backups
  }

seven_z_pw:
- {
    pw: "{{ vault_archive_pw }}",
    localfile: goinfra.7z,
    goinfra_archive_file: goinfradb.7z,
    k3s_archive_file: k3sdb.7z,
    goinfra_sql_file: go-infra.sql,
    k3s_sql_file: k3s.sql,
    path: /pgdumps,
    db_name: go-infra,
    goinfra_db_name: go-infra,
    k3s_db_name: k3s,
    db_user: jtrahan,
    k3s_db_user: k3suser
  }

primary_pg_server:
- { hostname: pgprime.trahan.dev }

pg_version: "15"
