postgresql_options:
- {name: listen_addresses, value: '0.0.0.0'}
- {name: wal_level, value: replica}
- {name: max_wal_senders, value: 5}
- {name: archive_mode, value: on}
- {name: archive_command, value: 'test ! -f /mnt/backups/pg_archive/%f && cp %p /mnt/backups/pg_archive/%f'}

postgresql_databases: [infradb-dev, automation-db]

postgresql_users:
- {db: infradb-dev, name: jtrahan, password: "{{ vault_postgresql_jtrahan_password }}"}
- {db: automation-db, name: replicator, password: "{{ vault_postgresql_replicator_password }}"}

postgresql_schemas:
- {db: infradb-dev, name: jtrahan, owner: jtrahan}
- {db: automation-db, name: replicator, owner: replicator}

postgresql_privs:
- {db: infradb-dev, roles: jtrahan, privs: ALL, type: database}
- {db: automation-db, roles: replicator, privs: ALL, type: database}

postgresql_hba_entries:
- {contype: local, databases: all, users: all, method: peer}
- {contype: host, databases: replication, users: replicator, address: trahdb2.trahan.dev, method: trust}
- {contype: host, databases: all, users: replicator, address: trahdb2.trahan.dev, method: trust}
- {contype: host, databases: all, users: jtrahan, address: trahdb2.trahan.dev, method: scram-sha-256}
- {contype: host, databases: all, users: all, method: scram-sha-256}
- {contype: host, databases: infradb-dev, users: jtrahan, address: samenet, method: scram-sha-256}
- {contype: host, databases: all, users: replicator, address: samenet, method: scram-sha-256}

postgresql_extensions:
- {db: infradb-dev, name: hstore,}

