version: "3.8"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus
    restart: on-failure
    volumes:
      - /mnt/share/gluster/prometheus:/etc/prometheus/
      - /mnt/share/gluster/prometheus/prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    networks:
      - ovnet1
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - ovnet1
    restart: on-failure
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager
    restart: on-failure
    ports:
      - 9093:9093
    volumes:
      - /mnt/share/gluster/alertmanager/:/etc/alertmanager/
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    networks:
      - ovnet1

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8580:8080
    networks:
      - ovnet1
    restart: on-failure
    deploy:
      mode: global

  grafana:
    image: grafana/grafana
    user: "472"
    restart: on-failure
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    volumes:
      - /mnt/share/gluster/grafana/grafana_data:/var/lib/grafana
      - /mnt/share/gluster/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - /mnt/share/gluster/grafana/config.monitoring
    networks:
      - ovnet1
    ports:
      - 3007:3000
    depends_on:
      - prometheus
networks:
  ovnet1:
    external: true
